apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: fairshare-scheduler
  plugins:
    preFilter:
      enabled:
      - name: FairShareGPU
    filter:
      enabled:
      - name: FairShareGPU
    score:
      enabled:
      - name: FairShareGPU
    postFilter:
      enabled:
      - name: FairShareGPU
    reserve:
      enabled:
      - name: FairShareGPU
